### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by nmn** [patr0nus/Pym#1]
Just wanted to know how it's possible to have a window with the blurred transparency in DeskGap. As I understand it, that is not possible with Electron.

Does using the system webView help make that possible?

**Comment by wan9chi** [comment]
Hi, actually it is [possible](https://electronjs.org/docs/api/browser-window#winsetvibrancytype-macos) in electron.

There is nothing much to do with the webview. Both DeskGap and electron use [NSVisualEffectView](https://developer.apple.com/documentation/appkit/nsvisualeffectview?language=objc) to achieve this effect.
